version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
    labels:
      - automerge
  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: daily
    labels:
      - automerge
  - package-ecosystem: docker
    directory: "/"
    schedule:
      interval: daily
    labels:
      - automerge
