name = "Startup"
uuid = "cd038ea3-df26-4edf-97c6-5148c252d028"
version = "0.1.0"
authors = ["Wen Wei Tseng <sosiristseng@gmail.com>"]

[deps]
PrecompileTools = "aea7be01-6a6a-4083-8856-8a6e6704d82a"

[compat]
PrecompileTools = "1.3.4"
