project:
  type: website
  output-dir: ../_site

website:
  title: "Quarto Julia Template"
  page-navigation: true
  back-to-top-navigation: true
  navbar:
    search: true
  sidebar:
    style: "docked"
    search: true
    contents: auto

format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    toc: true
    html-math-method: mathjax
