name: Check markdown links

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 1 * *' # Every month
  push:
    branches:
      - main
    paths:
      - 'docs/**'
      - '.github/workflows/linkcheck.yml'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  linkcheck:
    env:
      DIR: 'docs'
      PY_VER: '3.12'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PY_VER }}
      - name: Cache pip
        uses: actions/cache@v3
        id: cache-pip
        with:
          path: ${{ env.pythonLocation }}
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
      - name: Install python packages
        if: ${{ steps.cache-pip.outputs.cache-hit != 'true' }}
        run: pip install -r requirements.txt
      - name: Convert ipynb files to markdown
        run: >
          find ${{ env.DIR }} -type f -name '*.ipynb' |
          parallel -j2 jupyter nbconvert --to markdown {}
      - name: Restore lychee cache
        id: restore-cache
        uses: actions/cache/restore@v3
        with:
          path: .lycheecache
          key: cache-lychee-${{ github.sha }}
          restore-keys: cache-lychee-
      - name: Lychee Checker
        uses: lycheeverse/lychee-action@v1.9.1
        id: lychee
        with:
          fail: true
          args: --accept 200,204,429 --verbose --no-progress --cache --max-cache-age 1d "${{ env.DIR }}/**/*.md" "${{ env.DIR }}/**/*.qmd"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Save lychee cache
        uses: actions/cache/save@v3
        if: always()
        with:
          path: .lycheecache
          key: ${{ steps.restore-cache.outputs.cache-primary-key }}
